version: "3.9"
services:
  geth:
    hostname: geth
    build:
      context: .
      dockerfile: ./services/geth/Dockerfile
    restart: always
    command: 
      - --goerli
      - --datadir=/root/eth-data
      - --syncmode=snap
      - --http
      - --http.port=8545
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.api=eth,net,web3,
      - --authrpc.jwtsecret=/opt/jwtsecret
      - --authrpc.addr=geth
      - --authrpc.port=8551
      - --authrpc.vhosts=*
    volumes:
      - "/mnt/chaindata:/root/eth-data"
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 8545:8545
      - 8551:8551
    networks:
      - public
      - private
    
  prysm:
    hostname: prysm
    build:
      context: .
      dockerfile: ./services/prysm/Dockerfile    
    restart: always
    ports:
      - 4000:4000
      - 13000:13000/tcp
      - 12000:12000/udp
    volumes:
      - "/mnt/chaindata:/root/eth-data"
    command: --config-file=/opt/config.yaml
    networks:
      - public
      - private
networks:
  public:
  private:
    internal: true