version: "3.9"
services:
  geth:
    build:
      context: .
      dockerfile: ./docker/goerli/geth.Dockerfile
    restart: always
    command: 
      - --goerli
      - --datadir=/root/eth-data
      - --syncmode=snap
      - --http
      - --http.port=8545
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.api=eth,net,web3,
      - --authrpc.jwtsecret=/opt/jwtsecret
      - --authrpc.addr=geth
      - --authrpc.port=8551
      - --authrpc.vhosts=*
    volumes:
      - "/mnt/chaindata:/root/eth-data"
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 8545:8545
      - 8551:8551
    networks:
      - public
      - private 
  prysm:
    hostname: prysm
    build:
      context: .
      dockerfile: ./docker/goerli/prysm.Dockerfile    
    restart: always
    ports:
      - 4000:4000
      - 13000:13000/tcp
      - 12000:12000/udp
    volumes:
      - "/mnt/chaindata:/root/eth-data"
    command: --config-file=/opt/config.yaml
    networks:
      - public
      - private
  nitro:
    hostname: nitro
    image: offchainlabs/nitro-node:v2.0.11-8e786ec
    restart: always
    ports:
      - 9642:9642
      - 8547:8547
    volumes:
      - "/mnt/chaindata:/root/eth-data"
      - "/tmp/:/tmp/"
    command:
      - --l1.url=http://geth:8545
      - --l2.chain-id=421613
      - --http.api=net,web3,eth,debug
      - --http.corsdomain=*
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --ipc.path=ipc://tmp/arbitrum
    networks:
      - public
      - private
    ipc: "host"

networks:
  public:
  private:
    internal: true